language: java

jdk:
   - openjdk7

before_install:
   - mvn clean site

after_success:
 #  - mvn clean cobertura:cobertura 
   - mvn test

notifications:
  email:
      recipients:
         - senansenanc@gmail.com




